package me.itangqi.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BANNER".
 */
public class Banner {

    private Long id;
    private Integer adID;
    private String photo;
    private String alink;
    private String type;

    public Banner() {
    }

    public Banner(Long id) {
        this.id = id;
    }

    public Banner(Long id, Integer adID, String photo, String alink, String type) {
        this.id = id;
        this.adID = adID;
        this.photo = photo;
        this.alink = alink;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAdID() {
        return adID;
    }

    public void setAdID(Integer adID) {
        this.adID = adID;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getAlink() {
        return alink;
    }

    public void setAlink(String alink) {
        this.alink = alink;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
