package me.itangqi.greendao;

import me.itangqi.greendao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COUPON".
 */
public class Coupon {

    private Long id;
    private Long user_id;
    private Integer couponID;
    private String couponPics;
    private Integer width;
    private Integer height;
    private Integer couponPraise;
    private Boolean isPraise;
    private Boolean isCollect;
    private String intro;
    private String beginTime;
    private String lastTime;
    private String shopName;
    private Integer shopID;
    private Integer browserNum;

    /*人为添加，小心重置覆盖*/
    String collectNum;//(收藏量)
    /**/

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient CouponDao myDao;

    private User user;
    private Long user__resolvedKey;


    public Coupon() {
    }

    public Coupon(Long id) {
        this.id = id;
    }

    public Coupon(Long id, Long user_id, Integer couponID, String couponPics, Integer width, Integer height, Integer couponPraise, Boolean isPraise, Boolean isCollect, String intro, String beginTime, String lastTime, String shopName, Integer shopID, Integer browserNum) {
        this.id = id;
        this.user_id = user_id;
        this.couponID = couponID;
        this.couponPics = couponPics;
        this.width = width;
        this.height = height;
        this.couponPraise = couponPraise;
        this.isPraise = isPraise;
        this.isCollect = isCollect;
        this.intro = intro;
        this.beginTime = beginTime;
        this.lastTime = lastTime;
        this.shopName = shopName;
        this.shopID = shopID;
        this.browserNum = browserNum;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCouponDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public Integer getCouponID() {
        return couponID;
    }

    public void setCouponID(Integer couponID) {
        this.couponID = couponID;
    }

    public String getCouponPics() {
        return couponPics;
    }

    public void setCouponPics(String couponPics) {
        this.couponPics = couponPics;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getCouponPraise() {
        return couponPraise;
    }

    public void setCouponPraise(Integer couponPraise) {
        this.couponPraise = couponPraise;
    }

    public Boolean getIsPraise() {
        return isPraise;
    }

    public void setIsPraise(Boolean isPraise) {
        this.isPraise = isPraise;
    }

    public Boolean getIsCollect() {
        return isCollect;
    }

    public void setIsCollect(Boolean isCollect) {
        this.isCollect = isCollect;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public String getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }

    public String getLastTime() {
        return lastTime;
    }

    public void setLastTime(String lastTime) {
        this.lastTime = lastTime;
    }

    public String getShopName() {
        return shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    public Integer getShopID() {
        return shopID;
    }

    public void setShopID(Integer shopID) {
        this.shopID = shopID;
    }

    public Integer getBrowserNum() {
        return browserNum;
    }

    public void setBrowserNum(Integer browserNum) {
        this.browserNum = browserNum;
    }

    /** To-one relationship, resolved on first access. */
    public User getUser() {
        Long __key = this.user_id;
        if (user__resolvedKey == null || !user__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UserDao targetDao = daoSession.getUserDao();
            User userNew = targetDao.load(__key);
            synchronized (this) {
                user = userNew;
            	user__resolvedKey = __key;
            }
        }
        return user;
    }

    public void setUser(User user) {
        synchronized (this) {
            this.user = user;
            user_id = user == null ? null : user.getId();
            user__resolvedKey = user_id;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    public String getCollectNum() {
        return collectNum;
    }

    public void setCollectNum(String collectNum) {
        this.collectNum = collectNum;
    }
}
