package me.itangqi.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.itangqi.greendao.User;
import me.itangqi.greendao.New;
import me.itangqi.greendao.Mood;
import me.itangqi.greendao.Coupon;
import me.itangqi.greendao.Goods;
import me.itangqi.greendao.Banner;
import me.itangqi.greendao.MoodMessage;

import me.itangqi.greendao.UserDao;
import me.itangqi.greendao.NewDao;
import me.itangqi.greendao.MoodDao;
import me.itangqi.greendao.CouponDao;
import me.itangqi.greendao.GoodsDao;
import me.itangqi.greendao.BannerDao;
import me.itangqi.greendao.MoodMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig newDaoConfig;
    private final DaoConfig moodDaoConfig;
    private final DaoConfig couponDaoConfig;
    private final DaoConfig goodsDaoConfig;
    private final DaoConfig bannerDaoConfig;
    private final DaoConfig moodMessageDaoConfig;

    private final UserDao userDao;
    private final NewDao newDao;
    private final MoodDao moodDao;
    private final CouponDao couponDao;
    private final GoodsDao goodsDao;
    private final BannerDao bannerDao;
    private final MoodMessageDao moodMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        newDaoConfig = daoConfigMap.get(NewDao.class).clone();
        newDaoConfig.initIdentityScope(type);

        moodDaoConfig = daoConfigMap.get(MoodDao.class).clone();
        moodDaoConfig.initIdentityScope(type);

        couponDaoConfig = daoConfigMap.get(CouponDao.class).clone();
        couponDaoConfig.initIdentityScope(type);

        goodsDaoConfig = daoConfigMap.get(GoodsDao.class).clone();
        goodsDaoConfig.initIdentityScope(type);

        bannerDaoConfig = daoConfigMap.get(BannerDao.class).clone();
        bannerDaoConfig.initIdentityScope(type);

        moodMessageDaoConfig = daoConfigMap.get(MoodMessageDao.class).clone();
        moodMessageDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        newDao = new NewDao(newDaoConfig, this);
        moodDao = new MoodDao(moodDaoConfig, this);
        couponDao = new CouponDao(couponDaoConfig, this);
        goodsDao = new GoodsDao(goodsDaoConfig, this);
        bannerDao = new BannerDao(bannerDaoConfig, this);
        moodMessageDao = new MoodMessageDao(moodMessageDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(New.class, newDao);
        registerDao(Mood.class, moodDao);
        registerDao(Coupon.class, couponDao);
        registerDao(Goods.class, goodsDao);
        registerDao(Banner.class, bannerDao);
        registerDao(MoodMessage.class, moodMessageDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        newDaoConfig.getIdentityScope().clear();
        moodDaoConfig.getIdentityScope().clear();
        couponDaoConfig.getIdentityScope().clear();
        goodsDaoConfig.getIdentityScope().clear();
        bannerDaoConfig.getIdentityScope().clear();
        moodMessageDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public NewDao getNewDao() {
        return newDao;
    }

    public MoodDao getMoodDao() {
        return moodDao;
    }

    public CouponDao getCouponDao() {
        return couponDao;
    }

    public GoodsDao getGoodsDao() {
        return goodsDao;
    }

    public BannerDao getBannerDao() {
        return bannerDao;
    }

    public MoodMessageDao getMoodMessageDao() {
        return moodMessageDao;
    }

}
