package me.itangqi.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MOOD_MESSAGE".
 */
public class MoodMessage {

    private Long id;
    private Long user_id;
    private String message;
    private String bodyType;
    private String date;
    private String fromUserName;
    private String fromNickName;
    private Boolean hadRead;

    public MoodMessage() {
    }

    public MoodMessage(Long id) {
        this.id = id;
    }

    public MoodMessage(Long id, Long user_id, String message, String bodyType, String date, String fromUserName, String fromNickName, Boolean hadRead) {
        this.id = id;
        this.user_id = user_id;
        this.message = message;
        this.bodyType = bodyType;
        this.date = date;
        this.fromUserName = fromUserName;
        this.fromNickName = fromNickName;
        this.hadRead = hadRead;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getBodyType() {
        return bodyType;
    }

    public void setBodyType(String bodyType) {
        this.bodyType = bodyType;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getFromUserName() {
        return fromUserName;
    }

    public void setFromUserName(String fromUserName) {
        this.fromUserName = fromUserName;
    }

    public String getFromNickName() {
        return fromNickName;
    }

    public void setFromNickName(String fromNickName) {
        this.fromNickName = fromNickName;
    }

    public Boolean getHadRead() {
        return hadRead;
    }

    public void setHadRead(Boolean hadRead) {
        this.hadRead = hadRead;
    }

}
